class MainPageLocators:
    Base_URL = 'https://www.qa-practice.com/'
    Homepage = 'Homepage'
    Single_UI_Elements = '#sidebar > div > ul > li:nth-child(2)'
    Title_TEXT = '#content h1'
    Description_TEXT = '#content p:nth-child(2)'
    SELECT_Text_input = 'a[href="/elements/input/simple"]'
    SELECT_Simple_button = 'a[href="/elements/button/simple"]'
    SELECT_Single_checkbox = 'a[href="/elements/checkbox/single_checkbox"]'
    SELECT_Text_area = 'a[href="/elements/textarea/single"]'
    SELECT_Select_input = 'a[href="/elements/select/single_select"]'
    SELECT_New_tab = 'a[href="/elements/new_tab"]'
    SELECT_Alerts = 'a[href="/elements/alert"]'
    SELECT_Drag_and_Drop = 'a[href="/elements/dragndrop"]'
    SELECT_Iframes = 'a[href="/elements/iframe/iframe_page"]'
    SELECT_PopUp = 'a[href="/elements/popup"]'

class TextInputPageLocators:
    Inputs_URL = 'https://www.qa-practice.com/elements/input'
    Title_TEXT = '#content h1'
    Text_input_BUTTON = 'a[href="/elements/input/simple"]'
    Email_field_BUTTON = 'a[href="/elements/input/email"]'
    Password_field_BUTTON = 'a[href="/elements/input/passwd"]'
    Text_FIELD = '#id_text_string'
    Email_FIELD = '#id_email'
    Password_FIELD = '#id_password'
    Input_RESULT = '#result-text'

class SimpleButtonPageLocators:
    Buttons_URL = 'https://www.qa-practice.com/elements/button'
    Simple_BUTTON = 'a[href="/elements/button/simple"]'
    Looks_like_a_BUTTON = 'a[href="/elements/button/like_a_button"]'
    Disabled_BUTTON = 'a[href="/elements/button/disabled"]'
    Select_state_FIELD = '#id_select_state'
    Click_BUTTON = '#submit-id-submit'
    Click_looks_like_a_BUTTON = '#button-form > a'
    Submitted_TEXT = '#result-text'

class SingleCheckboxPageLocators:
    Checkbox_URL = 'https://www.qa-practice.com/elements/checkbox'
    Single_checkbox_BUTTON = 'a[href="/elements/checkbox/single_checkbox"]'
    Checkboxes_BUTTON = 'a[href="/elements/checkbox/mult_checkbox"]'
    Single_CHECKBOX = '#id_checkbox_0'
    One_CHECKBOX = '#id_checkboxes_0'
    Two_CHECKBOX = '#id_checkboxes_1'
    Three_CHECKBOX = '#id_checkboxes_2'
    Submit_BUTTON = '#submit-id-submit'
    Selected_CHECKBOXES = '#result-text'

class TextAreaPageLocators:
    Text_area_URL = 'https://www.qa-practice.com/elements/textarea'
    Textarea_BUTTON = 'a[href="/elements/textarea/single"]'
    Multiple_textareas_BUTTON = 'a[href="/elements/textarea/textareas"]'
    Text_area_FIELD = '#id_text_area'
    First_chapter_FIELD = '#id_first_chapter'
    Second_chapter_FIELD = '#id_second_chapter'
    Third_chapter_FIELD = '#id_third_chapter'
    Submit_BUTTON = '#submit-id-submit'
    Entered_TEXT = '#result-text'

class SelectInputPageLocators:
    Select_URL = 'https://www.qa-practice.com/elements/select'
    Single_select_BUTTON = 'a[href="/elements/select/single_select"]'
    Multiple_selects_BUTTON = 'a[href="/elements/select/mult_select"]'
    Choose_language_FIELD = '#id_choose_language'
    Choose_the_place_you_want_to_go_FIELD = '#id_choose_the_place_you_want_to_go'
    Choose_how_you_want_to_get_there_FIELD = '#id_choose_how_you_want_to_get_there'
    Choose_when_you_want_to_go_FIELD = '#id_choose_when_you_want_to_go'
    First_place_VALUE = '1', 'Sea'
    First_transport_VALUE = '1', 'Car'
    First_time_VALUE = '1', 'Today'
    Second_place_VALUE = '3', 'Old town'
    Second_transport_VALUE = '3', 'Train'
    Second_time_VALUE = '3', 'Next week'
    Submit_BUTTON = '#submit-id-submit'
    Submitted_TEXT = '#result-text'

class NewTabPageLocators:
    New_tab_URL = 'https://www.qa-practice.com/elements/new_tab'
    New_tab_link_BUTTON = 'a[href="/elements/new_tab/link"]'
    To_open_a_new_tab_LINK = 'a[href="/elements/new_tab/new_page"]'
    New_tab_button_BUTTON = 'a[href="/elements/new_tab/button"]'
    To_open_a_new_tab_BUTTON = '#new-page-button'
    New_tab_MESSAGE = '#result-text'

class AlertsPageLocators:
    Alerts_URL = 'https://www.qa-practice.com/elements/alert'
    Alert_BUTTON = 'a[href="/elements/alert/alert"]'
    Confirmation_BUTTON = 'a[href="/elements/alert/confirm"]'
    Prompt_BUTTON = 'a[href="/elements/alert/prompt"]'
    Click_BUTTON = '.a-button'
    Result = '#result-text'

class DragAndDropLocators:
    Drag_n_drop_URL = 'https://www.qa-practice.com/elements/dragndrop'
    Boxes_BUTTON = 'a[href="/elements/dragndrop/boxes"]'
    Drag_BOX = '#rect-draggable'
    Drop_BOX = '#rect-droppable'
    Result_BOX = '#text-droppable'
    Images_BUTTON = 'a[href="/elements/dragndrop/images"]'
    Drag_Image = '.rect-draggable'
    Drop_Image = '#rect-droppable2'
    Result_IMAGE = '#rect-droppable2'

class IframesPageLocators:
    Iframes_URL = 'https://www.qa-practice.com/elements/iframe'
    Iframe = '.embed-responsive-item'
    Navbar_ICON = '.navbar-toggler-icon'
    Footer_TEXT = "[class='mb-1']"  # Этот способ ищет элемент, где атрибут class полностью равен "mb-1"
    View_BUTTON = 'text=View'
    Edit_BUTTON = 'text=Edit'
    Visit_the_homepage_LINK = 'text=Visit the homepage'
    Card_Description_TEXT = '.card-text'

class PopUpPageLocators:
    PopUp_URL = 'https://www.qa-practice.com/elements/popup'
    Modal_BUTTON = 'a[href="/elements/popup/modal"]'
    Title_PopUp = '#exampleModalLabel'
    Checkbox = '.form-check-input'
    Iframe_PopUp_BUTTON = 'a[href="/elements/popup/iframe_popup"]'
    Launch_PopUp_BUTTON = '#content > button'
    Iframe = '.embed-responsive-item'
    Text_from_FRAME = '#text-to-copy'
    Close_BUTTON = 'Close'
    Check_BUTTON = 'Check'
    Send_BUTTON = 'Send'
    Text_FIELD = '#id_text_from_iframe'
    Submit_BUTTON = '#submit-id-submit'
    Result = '#result-text'
    Iframe_RESULT = '#check-result'